on: [push]
name: Azure RM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    
    steps:
    
    # Checkout code
    - uses: actions/checkout@main
    - name: Dir Files
      run: |
        dir
    
    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./Infrastructure/deploy-storaceaccount.bicep
        parameters: ./Infrastructure/deploy-storageaccount-parameters-dev.json
